### PR TITLE
updated resampy build to version 0.1.5

### PR DESCRIPTION
**Pull request by bmcfee**

### CODE REVIEW

**Comment by bmcfee** [comment]
@conda-forge/core This one's failing on appveyor, I think because it hasn't been re-rendered since conda-smithy 1.3.2.  Does that need to happen through @conda-forge-admin (as was done on another project i maintain), or is it something I can do via (this) PR?

**Comment by ocefpaf** [comment]
> or is it something I can do via (this) PR?

You can do it. Install `conda-smithy` from `conda-forge`,  issue `conda smithy rerender` from the recipe root, and commit the changes

**Comment by bmcfee** [comment]
Appveyor's now failing only for numpy 1.10 on python 3.6.  Curious.

**Comment by ocefpaf** [comment]
Update your `conda-smithy`. We dropped `numpy 1.10` in `conda-forge` and there is no version for `Python 3.6`.

**Comment by bmcfee** [comment]
Ah, my bad.  I'll try again with 1.7.  I had reverted to 1.6 earlier because of build errors, but it turned out to be a missing conda-build-all dependency.  It should work now.

**Comment by ocefpaf** [comment]
> Ah, my bad. I'll try again with 1.7.

Latest version is `2.0.1`, but I believe that 1.7 would do the trick here.

**Comment by bmcfee** [comment]
Yup, looks like 1.10 has been dropped from the build matrix in the queue.  Thanks!

**Pull request merged**
